-- Toscana Grill: instalación mínima completa para menú, pedidos, usuarios y dashboard.
create extension if not exists pgcrypto;

do $$ begin create type public.rol_usuario as enum ('administrador','caja','cocina','mesero'); exception when duplicate_object then null; end $$;
do $$ begin create type public.estado_pedido as enum ('pendiente','confirmado','en_preparacion','listo','entregado','cerrado','cancelado'); exception when duplicate_object then null; end $$;
do $$ begin create type public.tipo_pedido as enum ('mesa','para_llevar','delivery'); exception when duplicate_object then null; end $$;
do $$ begin create type public.estado_pago as enum ('pendiente','pagado','anulado'); exception when duplicate_object then null; end $$;
do $$ begin create type public.forma_pago as enum ('efectivo','transferencia','tarjeta','otro'); exception when duplicate_object then null; end $$;

create table if not exists public.perfiles(
  id uuid primary key references auth.users(id) on delete cascade,
  nombre_completo text not null,
  rol public.rol_usuario not null default 'mesero',
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);
create table if not exists public.mesas(
  id bigint generated by default as identity primary key,
  numero integer not null unique check(numero>0),
  nombre text,
  capacidad integer check(capacidad is null or capacidad>0),
  activa boolean not null default true,
  creada_en timestamptz not null default now()
);
create table if not exists public.categorias(
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  descripcion text,
  orden integer not null default 0,
  activa boolean not null default true,
  creada_en timestamptz not null default now()
);
create table if not exists public.productos(
  id bigint generated by default as identity primary key,
  categoria_id bigint references public.categorias(id) on delete set null,
  nombre text not null,
  descripcion text,
  precio numeric(10,2) not null check(precio>=0),
  imagen_url text,
  disponible boolean not null default true,
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);
create table if not exists public.pedidos(
  id uuid primary key default gen_random_uuid(),
  ticket text not null unique,
  token_consulta text not null unique,
  tipo public.tipo_pedido not null default 'mesa',
  mesa_id bigint references public.mesas(id) on delete set null,
  cliente_nombre text,
  cliente_telefono text,
  direccion_entrega text,
  estado public.estado_pedido not null default 'pendiente',
  estado_pago public.estado_pago not null default 'pendiente',
  forma_pago public.forma_pago,
  subtotal numeric(10,2) not null default 0,
  recargo numeric(10,2) not null default 0,
  descuento numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  observaciones text,
  creado_por uuid references public.perfiles(id) on delete set null,
  origen text not null default 'menu_publico' check(origen in('menu_publico','mesero','caja','administrador')),
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  cerrado_en timestamptz,
  check(tipo<>'mesa' or mesa_id is not null)
);
create table if not exists public.detalle_pedido(
  id bigint generated by default as identity primary key,
  pedido_id uuid not null references public.pedidos(id) on delete cascade,
  producto_id bigint references public.productos(id) on delete set null,
  producto_nombre text not null,
  cantidad integer not null check(cantidad>0),
  precio_unitario numeric(10,2) not null check(precio_unitario>=0),
  subtotal numeric(10,2) not null check(subtotal>=0),
  observaciones text,
  creado_en timestamptz not null default now()
);
create table if not exists public.historial_estado_pedido(
  id bigint generated by default as identity primary key,
  pedido_id uuid not null references public.pedidos(id) on delete cascade,
  estado_anterior public.estado_pedido,
  estado_nuevo public.estado_pedido not null,
  cambiado_por uuid references public.perfiles(id) on delete set null,
  observacion text,
  cambiado_en timestamptz not null default now()
);
create table if not exists public.pagos(
  id uuid primary key default gen_random_uuid(),
  pedido_id uuid not null references public.pedidos(id) on delete restrict,
  monto numeric(10,2) not null check(monto>0),
  forma_pago public.forma_pago not null,
  referencia text,
  registrado_por uuid references public.perfiles(id) on delete set null,
  registrado_en timestamptz not null default now(),
  anulado boolean not null default false,
  anulado_por uuid references public.perfiles(id) on delete set null,
  anulado_en timestamptz,
  motivo_anulacion text
);

create or replace function public.touch_updated_at() returns trigger language plpgsql set search_path='' as $$
begin new.actualizado_en=now(); return new; end $$;
drop trigger if exists perfiles_touch on public.perfiles;
create trigger perfiles_touch before update on public.perfiles for each row execute function public.touch_updated_at();
drop trigger if exists productos_touch on public.productos;
create trigger productos_touch before update on public.productos for each row execute function public.touch_updated_at();
drop trigger if exists pedidos_touch on public.pedidos;
create trigger pedidos_touch before update on public.pedidos for each row execute function public.touch_updated_at();

create or replace function public.crear_perfil_nuevo_usuario() returns trigger
language plpgsql security definer set search_path='' as $$
begin
 insert into public.perfiles(id,nombre_completo,rol,activo)
 values(new.id,coalesce(nullif(trim(new.raw_user_meta_data->>'nombre_completo'),''),split_part(new.email,'@',1),'Usuario'),'mesero',true);
 return new;
end $$;
drop trigger if exists crear_perfil_al_registrar_usuario on auth.users;
create trigger crear_perfil_al_registrar_usuario after insert on auth.users
for each row execute function public.crear_perfil_nuevo_usuario();

create or replace function public.rol_usuario_actual() returns public.rol_usuario
language sql stable security definer set search_path='' as $$
 select rol from public.perfiles where id=(select auth.uid()) and activo=true
$$;
create or replace function public.usuario_actual_activo() returns boolean
language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.perfiles where id=(select auth.uid()) and activo=true)
$$;
revoke all on function public.rol_usuario_actual() from public;
revoke all on function public.usuario_actual_activo() from public;
grant execute on function public.rol_usuario_actual() to authenticated;
grant execute on function public.usuario_actual_activo() to authenticated;

alter table public.perfiles enable row level security;
alter table public.mesas enable row level security;
alter table public.categorias enable row level security;
alter table public.productos enable row level security;
alter table public.pedidos enable row level security;
alter table public.detalle_pedido enable row level security;
alter table public.historial_estado_pedido enable row level security;
alter table public.pagos enable row level security;

grant select on public.mesas,public.categorias,public.productos to anon,authenticated;
grant select on public.perfiles,public.pedidos,public.detalle_pedido,public.historial_estado_pedido,public.pagos to authenticated;
grant usage,select on all sequences in schema public to authenticated;

drop policy if exists perfil_propio on public.perfiles;
create policy perfil_propio on public.perfiles for select to authenticated
using(id=(select auth.uid()) and activo=true);
drop policy if exists admin_perfiles on public.perfiles;
create policy admin_perfiles on public.perfiles for select to authenticated
using((select public.rol_usuario_actual())='administrador');

drop policy if exists mesas_publicas on public.mesas;
create policy mesas_publicas on public.mesas for select to anon,authenticated using(activa=true);
drop policy if exists categorias_publicas on public.categorias;
create policy categorias_publicas on public.categorias for select to anon,authenticated using(activa=true);
drop policy if exists productos_publicos on public.productos;
create policy productos_publicos on public.productos for select to anon using(activo=true and disponible=true);
drop policy if exists productos_personal on public.productos;
create policy productos_personal on public.productos for select to authenticated using(activo=true and (select public.usuario_actual_activo()));

drop policy if exists pedidos_admin_caja on public.pedidos;
create policy pedidos_admin_caja on public.pedidos for select to authenticated
using((select public.usuario_actual_activo()) and (select public.rol_usuario_actual()) in ('administrador','caja'));
drop policy if exists pedidos_cocina on public.pedidos;
create policy pedidos_cocina on public.pedidos for select to authenticated
using((select public.rol_usuario_actual())='cocina' and estado not in('cerrado','cancelado'));
drop policy if exists pedidos_mesero on public.pedidos;
create policy pedidos_mesero on public.pedidos for select to authenticated
using((select public.rol_usuario_actual())='mesero' and creado_por=(select auth.uid()));
drop policy if exists detalle_autorizado on public.detalle_pedido;
create policy detalle_autorizado on public.detalle_pedido for select to authenticated
using(exists(select 1 from public.pedidos p where p.id=detalle_pedido.pedido_id));
drop policy if exists historial_autorizado on public.historial_estado_pedido;
create policy historial_autorizado on public.historial_estado_pedido for select to authenticated
using(exists(select 1 from public.pedidos p where p.id=historial_estado_pedido.pedido_id));

create or replace function public.registrar_historial_estado() returns trigger
language plpgsql security definer set search_path='' as $$
begin
 if tg_op='INSERT' then
   insert into public.historial_estado_pedido(pedido_id,estado_anterior,estado_nuevo,cambiado_por)
   values(new.id,null,new.estado,auth.uid());
 elsif old.estado is distinct from new.estado then
   insert into public.historial_estado_pedido(pedido_id,estado_anterior,estado_nuevo,cambiado_por)
   values(new.id,old.estado,new.estado,auth.uid());
 end if;
 return new;
end $$;
drop trigger if exists pedido_historial_insert on public.pedidos;
create trigger pedido_historial_insert after insert on public.pedidos for each row execute function public.registrar_historial_estado();
drop trigger if exists pedido_historial_update on public.pedidos;
create trigger pedido_historial_update after update of estado on public.pedidos for each row execute function public.registrar_historial_estado();

create or replace function public.crear_pedido(
 p_tipo text,p_mesa_id bigint,p_cliente_nombre text,p_cliente_telefono text,
 p_direccion_entrega text,p_observaciones text,p_items jsonb
) returns jsonb language plpgsql security definer set search_path='' as $$
declare
 v_id uuid; v_ticket text; v_token text; v_tipo public.tipo_pedido; v_item jsonb;
 v_prod record; v_pid bigint; v_qty integer; v_sub numeric(10,2); v_total numeric(10,2):=0;
 v_user uuid; v_origin text:='menu_publico';
begin
 v_tipo:=p_tipo::public.tipo_pedido;
 if p_items is null or jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'El pedido debe contener productos.'; end if;
 if v_tipo='mesa' and not exists(select 1 from public.mesas where id=p_mesa_id and activa=true) then raise exception 'Mesa no válida.'; end if;
 if v_tipo='delivery' and nullif(trim(coalesce(p_direccion_entrega,'')),'') is null then raise exception 'Dirección requerida.'; end if;
 select id into v_user from public.perfiles where id=auth.uid() and activo=true;
 if v_user is not null then select case rol when 'mesero' then 'mesero' when 'caja' then 'caja' when 'administrador' then 'administrador' else 'menu_publico' end into v_origin from public.perfiles where id=v_user; end if;
 loop
  v_ticket:='TG-'||to_char(timezone('America/Guayaquil',now()),'YYYYMMDD')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,6));
  exit when not exists(select 1 from public.pedidos where ticket=v_ticket);
 end loop;
 v_token:=replace(gen_random_uuid()::text,'-','')||replace(gen_random_uuid()::text,'-','');
 insert into public.pedidos(ticket,token_consulta,tipo,mesa_id,cliente_nombre,cliente_telefono,direccion_entrega,observaciones,creado_por,origen)
 values(v_ticket,v_token,v_tipo,case when v_tipo='mesa' then p_mesa_id end,nullif(trim(coalesce(p_cliente_nombre,'')),''),
 nullif(trim(coalesce(p_cliente_telefono,'')),''),case when v_tipo='delivery' then nullif(trim(coalesce(p_direccion_entrega,'')),'') end,
 nullif(trim(coalesce(p_observaciones,'')),''),v_user,v_origin) returning id into v_id;
 for v_item in select value from jsonb_array_elements(p_items) loop
   v_pid:=(v_item->>'producto_id')::bigint; v_qty:=(v_item->>'cantidad')::integer;
   if v_qty is null or v_qty<=0 or v_qty>100 then raise exception 'Cantidad no válida.'; end if;
   select id,nombre,precio into v_prod from public.productos where id=v_pid and activo=true and disponible=true;
   if not found then raise exception 'Producto no disponible: %',v_pid; end if;
   v_sub:=round(v_prod.precio*v_qty,2);
   insert into public.detalle_pedido(pedido_id,producto_id,producto_nombre,cantidad,precio_unitario,subtotal,observaciones)
   values(v_id,v_prod.id,v_prod.nombre,v_qty,v_prod.precio,v_sub,nullif(trim(coalesce(v_item->>'observaciones','')),''));
   v_total:=v_total+v_sub;
 end loop;
 update public.pedidos set subtotal=v_total,total=v_total where id=v_id;
 return jsonb_build_object('pedido_id',v_id,'ticket',v_ticket,'token_consulta',v_token,'estado','pendiente','total',v_total);
end $$;
revoke all on function public.crear_pedido(text,bigint,text,text,text,text,jsonb) from public;
grant execute on function public.crear_pedido(text,bigint,text,text,text,text,jsonb) to anon,authenticated;

create or replace function public.listar_pedidos_activos()
returns table(pedido_id uuid,ticket text,tipo public.tipo_pedido,mesa_numero integer,mesa_nombre text,
 cliente_nombre text,estado public.estado_pedido,estado_pago public.estado_pago,total numeric,cantidad_items bigint,
 creado_por uuid,creado_por_nombre text,creado_en timestamptz,actualizado_en timestamptz)
language plpgsql security definer stable set search_path='' as $$
declare uid uuid; r public.rol_usuario;
begin
 select id,rol into uid,r from public.perfiles where id=auth.uid() and activo=true;
 if uid is null then raise exception 'Usuario no autenticado.'; end if;
 return query select p.id,p.ticket,p.tipo,m.numero,m.nombre,p.cliente_nombre,p.estado,p.estado_pago,p.total,
 coalesce(sum(d.cantidad),0)::bigint,p.creado_por,pr.nombre_completo,p.creado_en,p.actualizado_en
 from public.pedidos p left join public.mesas m on m.id=p.mesa_id left join public.detalle_pedido d on d.pedido_id=p.id
 left join public.perfiles pr on pr.id=p.creado_por
 where p.estado not in('cerrado','cancelado') and (r in('administrador','caja','cocina') or (r='mesero' and p.creado_por=uid))
 group by p.id,m.numero,m.nombre,pr.nombre_completo order by p.creado_en;
end $$;
revoke all on function public.listar_pedidos_activos() from public;
grant execute on function public.listar_pedidos_activos() to authenticated;

create or replace function public.obtener_detalle_pedido(p_pedido_id uuid) returns jsonb
language plpgsql security definer stable set search_path='' as $$
declare uid uuid;r public.rol_usuario;p record;items jsonb;
begin
 select id,rol into uid,r from public.perfiles where id=auth.uid() and activo=true;
 if uid is null then raise exception 'Usuario no autenticado.'; end if;
 select pe.*,m.numero mesa_numero,m.nombre mesa_nombre into p from public.pedidos pe left join public.mesas m on m.id=pe.mesa_id where pe.id=p_pedido_id;
 if not found then raise exception 'Pedido no encontrado.'; end if;
 if r='mesero' and p.creado_por is distinct from uid then raise exception 'Acceso denegado.'; end if;
 select coalesce(jsonb_agg(jsonb_build_object('producto',producto_nombre,'cantidad',cantidad,'precio_unitario',precio_unitario,'subtotal',subtotal,'observaciones',observaciones) order by id),'[]'::jsonb)
 into items from public.detalle_pedido where pedido_id=p_pedido_id;
 return jsonb_build_object('pedido_id',p.id,'ticket',p.ticket,'tipo',p.tipo,'mesa',case when p.tipo='mesa' then jsonb_build_object('numero',p.mesa_numero,'nombre',p.mesa_nombre) end,
 'estado',p.estado,'estado_pago',p.estado_pago,'total',p.total,'observaciones',p.observaciones,'creado_en',p.creado_en,'detalle',items);
end $$;
revoke all on function public.obtener_detalle_pedido(uuid) from public;
grant execute on function public.obtener_detalle_pedido(uuid) to authenticated;

create or replace function public.resumen_diario(p_fecha date default null) returns jsonb
language plpgsql security definer stable set search_path='' as $$
declare uid uuid;r public.rol_usuario;f date;tot int;act int;cerr int;can int;ventas numeric;pagado numeric;
begin
 select id,rol into uid,r from public.perfiles where id=auth.uid() and activo=true;
 if uid is null or r not in('administrador','caja') then raise exception 'Acceso denegado.'; end if;
 f:=coalesce(p_fecha,timezone('America/Guayaquil',now())::date);
 select count(*)::int,count(*) filter(where estado not in('cerrado','cancelado'))::int,count(*) filter(where estado='cerrado')::int,
 count(*) filter(where estado='cancelado')::int,coalesce(sum(total) filter(where estado<>'cancelado'),0)
 into tot,act,cerr,can,ventas from public.pedidos where timezone('America/Guayaquil',creado_en)::date=f;
 select coalesce(sum(pg.monto),0) into pagado from public.pagos pg join public.pedidos p on p.id=pg.pedido_id
 where timezone('America/Guayaquil',pg.registrado_en)::date=f and pg.anulado=false and p.estado<>'cancelado';
 return jsonb_build_object('fecha',f,'total_pedidos',tot,'pedidos_activos',act,'pedidos_cerrados',cerr,'pedidos_cancelados',can,
 'ventas_generadas',round(ventas,2),'total_pagado',round(pagado,2));
end $$;
revoke all on function public.resumen_diario(date) from public;
grant execute on function public.resumen_diario(date) to authenticated;

insert into public.mesas(numero,nombre,capacidad) values
(1,'Mesa 1',4),(2,'Mesa 2',4),(3,'Mesa 3',4),(4,'Mesa 4',4),(5,'Mesa 5',4),
(6,'Mesa 6',4),(7,'Mesa 7',6),(8,'Mesa 8',6),(9,'Mesa 9',2),(10,'Mesa 10',2)
on conflict(numero) do update set nombre=excluded.nombre,capacidad=excluded.capacidad;

insert into public.categorias(nombre,descripcion,orden) values
('Entradas','Entradas y aperitivos',10),('Platos principales','Platos principales',20),('Bebidas','Bebidas',30),('Postres','Postres',40)
on conflict(nombre) do nothing;

insert into public.productos(categoria_id,nombre,descripcion,precio)
select id,'Pizza Toscana','Pizza especial de la casa',12.50 from public.categorias where nombre='Platos principales'
and not exists(select 1 from public.productos where nombre='Pizza Toscana');
insert into public.productos(categoria_id,nombre,descripcion,precio)
select id,'Limonada','Limonada natural',2.50 from public.categorias where nombre='Bebidas'
and not exists(select 1 from public.productos where nombre='Limonada');

-- Después de crear el primer usuario, reemplaza el correo:
-- update public.perfiles p set nombre_completo='Administrador Toscana Grill',rol='administrador',activo=true
-- from auth.users u where p.id=u.id and lower(u.email)=lower('TU_CORREO');
